### PR TITLE
run-config: Delete config folder.

### PR DESCRIPTION
**Pull request by soerendomroes**
The config repo does not exist anymore and should have never been in
there.

I do not know why klighd is an internalArchive for me (and an external on the master). Maybe @NiklasRentzCAU knows something about it.

### CODE REVIEW

**Comment by NiklasRentzCAU** [comment]
Yeah, the config repo is not necessary, probably was an oversight when just adding "everything".

I don't know what the internal/external archive does. Did you notice any change when executing it as one or the other or found the documentation for that?

**Comment by soerendomroes** [comment]
@NiklasRentzCAU @a-sr Can someone please approve and merge this?

**Comment by NiklasRentzCAU** [comment]
I asked a question before regarding the other change of this PR that neither you nor I know something about yet, have you looked into that? I did not want to accept a change with unknown effect.
Merging can then only be done by als.

**Review by a-sr — APPROVED** [review]
Ok

**Pull request merged**
